AWSTemplateFormatVersion: "2010-09-09"
Description: Create an ec2 instance with security group using cloudformation

Parameters:
  MyVPC:
    Type: AWS::EC2::VPC::Id
    Description: Select your vpc
    
  MySubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Select a subnet in the VPC (public subnet recommended)

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access 
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22 
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 

      Tags:
        - Key: Name
          Value: MyCFTSecurityGroup


  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: awsdemo
      ImageId: ami-0a716d3f3b16d290c
      SubnetId: !Ref MySubnet
      SecurityGroupIds:
        - !Ref MySecurityGroup

      Tags:
        - Key: Name
          Value: MyEC2Instance
            

   
     